# Generated by Django 5.2 on 2026-04-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('course', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('git_url', models.URLField()),
                ('linked_url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoal',
        ),
    ]
