# Generated by Django 5.2 on 2026-04-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personal_delete_pessoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('course', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('git', models.URLField()),
                ('linked', models.URLField()),
                ('url_imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
