# Generated by Django 5.2 on 2026-04-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_delete_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url_imagem',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
